blueprint:
  domain: automation
  name: Music Assistant - Support de voix en mode local - Blueprint
  source_url: https://github.com/music-assistant/voice-support/blob/main/local-assist-blueprint/mass_assist_blueprint_fr.yaml
  description: " ![Image](https://github.com/music-assistant/voice-support/blob/main/assets/music-assistant.png?raw=true)

    # Lire des fichiers multimédias à l'aide de commandes vocales

    ### Configuration du Blueprint

    #### Obligatoire

    * Définissez un « Lecteur par défaut » à utiliser lorsqu'aucune cible n'est mentionnée dans la requête
    et que la requête ne provient pas d'une zone équipée d'un lecteur Music Assistant.

    #### Facultatif

    * Modifiez la phrase déclencheuse ou ajoutez-en d'autres ; vous pouvez également l'utiliser pour traduire
    la phrase dans votre propre langue.

    * Modifiez les réponses ou traduisez-les dans votre propre langue.


    ### Utilisation

    Toutes les phrases doivent :

    * commencer par les mots « Jouer»,  « Ecouter » ou « Lire », suivis du type d'élément « artist »/« chanson»/« album »/« playlist »/« radio »/« audio livre » puis du nom de l'élément.

    * les albums et les chansons peuvent être éventuellement suivie de « par [l']artiste », puis du nom de l'artiste

    * peuvent éventuellement être suivie d'un nom de zone ou d'un nom d'appareil

    * finalement, pour les artistes, chansons, albums ou listes de lecture, être éventuellement suivie de la phrase « en mode radio » ou « en mode aléatoire »

    #### Variantes acceptées

    l'utilisation des articles « le »,« la »,« l' » est facultative

    |Type de média|Variantes acceptées|

    |---|---|

    |« artiste »|« groupe »|

    |« piste »|« chanson »|

    |« radio »|« station de radio »|

    |« playlist »|« liste de lecture »|


    #### Exemples

    ```

    Jouer l'artiste Jean-Jacques Goldman dans la cuisine

    Écouter l'album Mistral Gagnant dans le bureau

    Lire l'album Débranche de l'artiste France Gall dans la cuisine

    Jouer la chanson Désenchantée dans la chambre

    Écouter chanson Désenchantée en mode radio dans la chambre

    Écouter la piste Les Champs-Élysées de Joe Dassin dans la chambre

    Écouter la liste de lecture Chansons Françaises dans le bureau

    Lire la playlist Chansons Françaises dans le bureau

    Jouer la station de radio France Inter dans la chambre

    Écouter l'album Le Grand Bleu sur l'enceinte Sonos de la chambre

    Écouter le groupe Indochine

    Écouter le groupe Daft Punk en mode aléatoire.

    Écouter l'album Le Grand Bleu en mode aléatoire sur l'enceinte Sonos de la chambre

    Lire le livre audio Le Petit Prince

    ```"
  input:
    default_player_entity_id_input:
      name: Default Media Player
      selector:
        entity:
          filter:
          - integration: music_assistant
            domain:
            - media_player
          multiple: false
    trigger_response_settings:
      name: Trigger and response settings for Assist
      icon: mdi:chat
      description: "Vous pouvez modifier les déclencheurs existants ou en ajouter d'autres dans ces
        paramètres. Placez le texte entre crochets [ ] pour le rendre facultatif. Avec des
        parenthèses ( ) et un caractère pipe |, vous pouvez saisir plusieurs valeurs qui seront
        traitées comme un « ou ». { query } est une valeur générique qui contiendra le média
        demandé et, éventuellement, la zone ou le lecteur Music Assistant.

        Vous pouvez également définir les réponses qu'Assist fournira. Il utilise des modèles Jinja qui
        seront remplacés par les informations sur le média et le nom du lecteur Music Assistant."
      collapsed: true
      input:
        album_trigger:
          name: Album trigger
          description: The trigger sentences to request a specific album.
          selector:
            text:
              multiline: false
              multiple: true
          default:
          - "(lire|écouter|jouer|play) [la| le
            |l'](album|EP|disque|compilation|single) {media_name} [par [le |la
            |l'](artiste|groupe|formation) {artist}] [(dans|sur) [le
            ]{area_or_player_name}][ (avec|en) {radio_mode}][ (avec|en) {shuffle}]"
        track_trigger:
          name: Track trigger
          description: Les phrases déclancheurs permettant de demander une chanson en particulier.
          selector:
            text:
              multiline: false
              multiple: true
          default:
          - "(lire|écouter|jouer|play) [le |la ](morceau|chanson)
            {media_name} [par [le |la |l'](artiste|groupe|formation) {artist}]
            [(dans|sur) [le ]{area_or_player_name}][ (avec|en) {radio_mode}][ (avec|en) {shuffle}]"
        artist_trigger:
          name: Artist trigger
          description: Les phrases déclancheurs permettant de demander de la musique d'un artiste spécifique.
          selector:
            text:
              multiline: false
              multiple: true
          default:
          - "(lire|écouter|jouer|play) [le |l'|la
            ](artiste|groupe|formation) {media_name} [(dans|sur) [le
            ]{area_or_player_name}][ (avec|en) {radio_mode}][ (avec|en) {shuffle}]"
        audiobook_trigger:
          name: Audiobook trigger
          description: Les phrases déclancheurs permettant de demander un livre audio.
          selector:
            text:
              multiline: false
              multiple: true
          default:
          - "(écouter|jouer|play) [le |l'|la ](livre|audio livre|livre audio) {media_name} [(in|on|using)
            [the ]{area_or_player_name}]"
        radio_trigger:
          name: Radio trigger
          description: Les phrases déclancheurs permettant de demander une station de radio spécifique.
          selector:
            text:
              multiline: false
              multiple: true
          default:
          - "(lire|écouter|jouer|play) [le |l'|la ]((station de
            radio)|(radio)|(station)) {media_name} [(dans|sur) [la
            ]{area_or_player_name}]"
        playlist_trigger:
          name: Playlist trigger
          description: Les phrases déclancheurs permettant de demander une liste de lecture spécifique.
          selector:
            text:
              multiline: false
              multiple: true
          default:
          - "(lire|écouter|jouer|play) [la ](liste|liste de
            lecture|playlist) {media_name} [(dans|sur) [la ]{area_or_player_name}][
            (avec|en) {radio_mode}][ (avec|en) {shuffle}]"
triggers:
  - trigger: conversation
    command: !input album_trigger
    id: album
  - trigger: conversation
    command: !input track_trigger
    id: track
  - trigger: conversation
    command: !input artist_trigger
    id: artist
  - trigger: conversation
    command: !input radio_trigger
    id: radio
  - trigger: conversation
    command: !input playlist_trigger
    id: playlist
actions:
- alias: Définissez les variables à utiliser dans l'automatisation
  variables:
    version: 20260601
    shuffle: '{{ ''aléatoire'' in trigger.sentence | lower }}'
    default_player_entity_id: !input default_player_entity_id_input
    trigger_id: '{{ trigger.id }}'
    area_or_player_name: '{{ trigger.slots.area_or_player_name | default }}'
    assist_device_id: '{{ trigger.device_id }}'
    action_data:
      media_id: '{{ trigger.slots.media_name }}'
      media_type: '{{ ''radio'' if ''radio'' in media_name | lower else trigger_id
        }}'
      artist: '{{ trigger.slots.artist | default }}'
      radio_mode: '{{ ''radio'' in trigger.slots.radio_mode | default | lower }}'
    ma_players: '{{  integration_entities(''music_assistant'') | select(''match'', ''media_player'') | list }}'
    player_entity_id_by_player_name: "{{ ma_players |
      expand \n  | selectattr('name', 'match', area_or_player_name ~ '$', ignorecase=true)\n
      \ | map(attribute='entity_id') | list }}\n"
    player_entity_id_by_area_name: '{{ areas() | map(''area_name'') | select(''match'',
      area_or_player_name ~ ''$'',  ignorecase=true) | map(''area_entities'') | sum(start=[])
      | select(''in'',  ma_players) | list }}

      '
    player_entity_id_by_assist_area: '{{ area_entities(area_id(trigger.device_id))
      | select(''in'', ma_players) | list }}

      '
    mass_player_entity_id: "{{ player_entity_id_by_player_name or player_entity_id_by_area_name
      \nor player_entity_id_by_assist_area or [default_player_entity_id] }}\n"
    mass_player_name: '{{ mass_player_entity_id | map(''state_attr'', ''friendly_name'')
      | join('', '') }}'
- alias: Envoyer le média au lecteur Music Assistant sélectionné
  action: music_assistant.play_media
  data: '{{ dict(action_data.items() | selectattr(''1'')) }}'
  target:
    entity_id: '{{ mass_player_entity_id }}'
- alias: Activer/Désactiver le mode aléatoire sur un lecteur Media Player Music Assistant
  action: media_player.shuffle_set
  data:
    shuffle: '{{ shuffle }}'
  target:
    entity_id: '{{ mass_player_entity_id }}'
- alias: Envoyer la réponse
  set_conversation_response: >-
    {{ '' if 'mélanger | aléatoire' in trigger.sentence | lower  else 'Je
    joues'}} {{ trigger.slots.media_name }} {{ '' if 'mélanger | aléatoire' in
    trigger.sentence | lower else ''}} sur {{ mass_player_name }}
mode: single
